### ISSUE TITLE
Issue with warnings appearing to redraw micro

### ISSUE THREAD

**Issue by FerretCode** [AndCake/micro-plugin-lsp#20]
Hey there! Super excited for this project, I've been looking forward to micro getting LSP support. 

Anyways, I was testing the plugin with JavaScript, and I noticed that every time I start typing and there's a warning, it looks like micro re-draws and it's been bugging me. Here's a gif of it happening: https://ibb.co/h770MqB 

Is this intended behavior? If so, is there a way to disable it?

Thanks in advance,
ferretcode

**Comment by AndCake** [comment]
Hi! Yes I see what you mean. While typing, the plugin sends the changed contents of the document over to the language server to keep him informed. The language server in turn replies with some warnings that the code won't compile (because it's unfinished). Do you think it would work for you if the warnings are not added while you are working in the line the warning is for?

**Comment by AndCake** [comment]
@FerretCode : I added a PR to address the issue. Can you checkout the branch `feature/20-skip-inprogress-messages` and see if this works for you?

**Comment by FerretCode** [comment]
@AndCake Sounds good, thank you.
